services:
  frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile
    image: car-frontend:latest
    ports:
      - 3000:5173
    depends_on:
      - backend
    volumes:
      - ./react_frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: car-backend:latest
    ports:
      - 5000:5000
