services:
  frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile
    image: car-frontend:latest
    container_name: car-rental-frontend
    ports:
      - 3000:5173
    depends_on:
      - backend
    volumes:
      - ./react_frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: car-backend:latest
    container_name: car-rental-backend
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: car-rental-db
    ports:
      - "3306:3306"
    secrets:
      - db-root-password
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=Real_Fake_Car_Rentals
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
  seeder:
    build:
      context: ./
      dockerfile: Dockerfile
    image: car-seeder:latest
    container_name: car-rental-seeder
    volumes:
      - ./database:/app/database # Persist the marker file
      - ./.env:/app/.env
    depends_on:
      - db
volumes:
  db-data:
secrets:
  db-root-password:
    file: ./.secrets/db-root-password.txt
